### ISSUE TITLE
Checkstyle bug: mutli arguments as lambdas  indentation

### ISSUE THREAD

**Issue by BinaryIgor** [yegor256/qulice#985] opened 2019-01-17 20:19 UTC
As described, checkstyle is saying that identation is not incorrect, when in fact it is. 
![ctor](https://user-images.githubusercontent.com/41533396/51346155-38676a80-1a9d-11e9-8abd-9e773f64df78.JPG)
Message:
![lambda](https://user-images.githubusercontent.com/41533396/51346166-40bfa580-1a9d-11e9-8379-7a6f4c095065.JPG)
Super ctor:
![super_ctor](https://user-images.githubusercontent.com/41533396/51346241-6e0c5380-1a9d-11e9-81f4-d8e189d24288.JPG)
Are parameters are Functional Interfaces.

**Comment by 0crat** [comment] 2019-01-17 20:19
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-01-17 20:19
@iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by victornoel** [comment] 2019-07-13 09:58
@krzyk @Iprogrammerr this is a duplicate of #898

**Comment by yegor256** [comment] 2024-05-16 12:36
dup of #898

**Closed by yegor256** 2024-05-16 12:36 UTC
